title: Streamify
author: GitHub User timjoschneider
email: timjoschneider@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Streamify will change any user xperience that have been seen before

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
https://github.com/timjoschneider:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
